spring:
  application:
    name: springboot-oauth2-google
  datasource:
    url: jdbc:hsqldb:file:./hsql-db/oauth2-google/db
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 972753554155-10fuc00dd86cpq1e0hcsq7f3rhb4uhfc.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: email

server:
  port: 8080