server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8061/eureka/

spring:
  application:
    name: student-service
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:hsqldb:file:./hsql-db/ms/auth/student/db
    username: sa
    password:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://zipkin:9411
    sender:
      type: web

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logging: # in alternativa una logback.xml. Questo è più snello ma meno configurabile
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    root: INFO
    org.springframework.web: INFO
    it.unical.inf.ea.uniprjms: INFO

springdoc:
  packages-to-scan: it.unical.inf.ea.uniprjms.student
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    groups:
      enabled: true

jwt:
  secret: ZNAUhywjWMxENUeQvxjmDSfbNHaJeYmecN4pGHgZxQMqgdHZGLNejvtP9PuXCmE6 # si potrebbe centrallizare inserirela in un punto comume o costante in SHARED o variabile di sistema
  security:
    enabled: true
    publicPaths: /v3/api-docs/**, /swagger-ui/**, /swagger-ui.html, /students
    protectedRoutes:
      /students/{idStudent}: ROLE_ADMIN, ROLE_USER
      /students/search: ROLE_USER
      /students/POST: ROLE_ADMIN
      /students/{idStudent}/PUT: ROLE_ADMIN
      /students/{idStudent}/DELETE: ROLE_ADMIN

cors:
  allowed-origins: http://localhost:3000, http://localhost:8060


---
# PROFILO DOCKER
spring:
  config:
    activate:
      on-profile: docker
  application:
    name: student-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8061/eureka/

# DISABILITA ZIPKIN E TRACING
management:
  tracing:
    enabled: false
  zipkin:
    tracing:
      enabled: false

# Logging senza tracing
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
