server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8061/eureka/

spring:
  application:
    name: teacher-service
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:hsqldb:file:./hsql-db/ms/auth/teacher/db
    username: sa
    password:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://zipkin:9411
    sender:
      type: web

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logging: # in alternativa una logback.xml. Questo è più snello ma meno configurabile
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packages-to-scan: it.unical.inf.ea.uniprjms.teacher
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    groups:
      enabled: true

jwt:
  secret: ZNAUhywjWMxENUeQvxjmDSfbNHaJeYmecN4pGHgZxQMqgdHZGLNejvtP9PuXCmE6 # si potrebbe centrallizare inserirela in un punto comume o costante in SHARED o variabile di sistema
  security:
    enabled: true
    publicPaths: /v3/api-docs/**, /swagger-ui/**, /swagger-ui.html
    protectedRoutes:
      /teacher/{id}: ROLE_USER
      /teachers: ROLE_USER

cors:
  allowed-origins: http://localhost:3000, http://localhost:8060

---
# PROFILO DOCKER
# PROFILO DOCKER
spring:
  config:
    activate:
      on-profile: docker
  application:
    name: teacher-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8061/eureka/

# DISABILITA ZIPKIN E TRACING
management:
  tracing:
    enabled: false
  zipkin:
    tracing:
      enabled: false

# Logging senza tracing
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
