version: '3.8'

# docker compose -p uniprj_rabbitmq-zipkin up
# RabbitMQ Management: http://localhost:15672/ (guest/guest)
# Zipkin: http://localhost:9411/zipkin/

services:
        rabbitmq:
                image: rabbitmq:3-management
                container_name: rabbitmq
                ports:
                        - "5672:5672"   # Porta AMQP
                        - "15672:15672" # Porta interfaccia web di management
                environment:
                        RABBITMQ_DEFAULT_USER: guest
                        RABBITMQ_DEFAULT_PASS: guest

        zipkin:
                image: openzipkin/zipkin
                container_name: zipkin
                ports:
                        - "9411:9411" # Porta UI di Zipkin
                environment:
                        - STORAGE_TYPE=mem
                restart: always
